#!/usr/bin/env bash
#Install nginx and configure
sudo pt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
